sdk: fix typing-extensions already installed by apt
1. fix install conflict on ubuntu.
```
Installing collected packages: typing-extensions, setuptools, protobuf, grpcio, grpcio-tools, conch
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.10.0
ERROR: Cannot uninstall typing_extensions 4.10.0, RECORD file not found. Hint: The package was installed by debian.
Error: Failed to install SDK with pip.
make: *** [Makefile:124：install] 错误 1
```

2. print warning message when proxy enabled.
3. add python-api docs.

Signed-off-by: micky <mickyching@qq.com>